### ISSUE TITLE
[Bug] Flatpak version 1.5.3 fails to start on Wayland

### ISSUE THREAD

**Issue by Laertes87** [flathub/dev.vencord.Vesktop#27]
I could work around this issue for now by disabling Wayland for the app using Flatseal.

### Operating System

Fedora 40

### Linux Only ~ Desktop Environment

Gnome on Wayland

### What happens when the bug or crash occurs?

When trying to start Vesktop on Wayland nothing happens. Trying to start it using the `flatpak run` command in a terminal reveals an error. I'm not entirely sure if it's a Vesktop or a Vencord issue. But it only started happening after updating the Flatpak to version 1.5.3

### What is the expected behaviour?

I expect Vesktop to just start normally on Wayland.

### How do you recreate this bug or crash?

1. Update to the latest version of the Flatpak
2. Open a terminal and run `flatpak run dev.vencord.Vesktop`
3. Observe error

### Debug Logs

```
$ flatpak run dev.vencord.Vesktop 
Using NVIDIA on Wayland, disabling gpu sandbox
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --disable-gpu-sandbox --ozone-platform-hint=auto
[3:0705/102833.041218:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:0705/102833.227227:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[3:0705/102833.227260:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[66:0705/102833.263201:ERROR:v8_initializer.cc(808)] V8 process OOM (Failed to reserve virtual memory for CodeRange).
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[3:0705/102833.335198:ERROR:browser_main_loop.cc(278)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[122:0705/102833.346573:ERROR:v8_initializer.cc(808)] V8 process OOM (Failed to reserve virtual memory for CodeRange).
[3:0705/102833.378600:ERROR:wayland_event_watcher.cc(43)] libwayland: [destroyed object]: error 7: failed to import supplied dmabufs: Could not bind the given EGLImage to a CoglTexture2D

/app/bin/startvesktop: Zeile 22:     3 Trace/Breakpoint ausgelöst   zypak-wrapper /app/bin/vesktop/vesktop.bin "${FLAGS[@]}" "$@"
```

**Comment by Vendicated** [comment]
should be fixed via https://github.com/flathub/dev.vencord.Vesktop/pull/28

**Comment by Laertes87** [comment]
I still get that error after updating to the version that includes the mentioned PR.

```
$ flatpak run dev.vencord.Vesktop 
Using NVIDIA on Wayland, disabling gpu sandbox
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --disable-gpu-sandbox --ozone-platform-hint=auto
[3:0705/202240.312190:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[3:0705/202240.499400:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[3:0705/202240.499438:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[3:0705/202240.610678:ERROR:browser_main_loop.cc(278)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[3:0705/202240.645321:ERROR:wayland_event_watcher.cc(43)] libwayland: [destroyed object]: error 7: failed to import supplied dmabufs: Could not bind the given EGLImage to a CoglTexture2D

/app/bin/startvesktop: Zeile 26:     3 Trace/Breakpoint ausgelöst   zypak-wrapper /app/bin/vesktop/vesktop.bin "${FLAGS[@]}" "$@"
```
